# Pushされるごとに自動ビルド/テスト/コーディング規約チェックをする。
#
# 全てのcommit/pushに対して実行可能・一定の品質・可読しやすいコードである事を要求する。
---
name: Build/Test/Lint
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  # 動作確認しやすいように手動起動をサポートする。
  workflow_dispatch:
  push:
    branches: [main]

# ワークフローレベルでパーミッションをすべて無効化する。
permissions: {}

# デフォルトシェルでパイプエラーを有効化する。
defaults:
  run:
    shell: bash

# ワークフローが複数起動したら自動キャンセルする。
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build, Test and Lint.
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # ソースをチェックアウトする。
      - uses: actions/checkout@v4

      # Node.jsをインストールする。
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm run test:unit

      - name: Setup Playwright
        run: npx playwright install --with-deps chromium

      - name: E2E Tests
        run: npm run test:e2e

      - name: Lint
        run: npm run lint

      - name: JSconfig
        run: npm run check
